### ISSUE TITLE
Report items that didn't appear in the world analyzer here

### ISSUE THREAD

**Issue by Razzmatazzz** [Razzmatazzz/RemnantSaveGuardian#43]
If you found an item that didn't appear in the world analyzer, please report it here. Please indicate the world and event (with a link to the [wiki page](https://remnant2.wiki.fextralife.com)) in which you received the item. Also please export your save via the world analyzer after you pick up the item and post the files here. Indicate whether it was your first, second, third, etc. character.

**Comment by Wuxriff** [comment]
[Temp.zip](https://github.com/Razzmatazzz/RemnantSaveGuardian/files/12292456/Temp.zip)
https://remnant2.wiki.fextralife.com/Propulsion+Loop
https://remnant2.wiki.fextralife.com/Low+Yield+Recovery+Ring

 /Game/World_Nerud/Items/Trinkets/Rings/PropulsionLoop/Ring_PropulsionLoop.Ring_PropulsionLoop_C
/Game/World_Nerud/Items/Trinkets/Rings/LowYieldRecoveryRing/Ring_LowYieldRecoveryRing.Ring_LowYieldRecoveryRing_C

N'Erud / Spectrum Nexus

**Comment by cheerbo** [comment]
I don't have the save anymore, but in case someone does, these two items are missing from the world analyzer:
https://remnant2.wiki.fextralife.com/Lithic+Signet from 4 statues event on Yaesha
https://remnant2.wiki.fextralife.com/Kuri+Kuri+Charm from https://remnant2.wiki.fextralife.com/Bird's+Nest event on Yaesha

**Comment by Razzmatazzz** [comment]
@cheerbo Can you export your save that included these items via the world analyzer and post them here?

**Comment by sinnoaria** [comment]
![image](https://github.com/Razzmatazzz/RemnantSaveGuardian/assets/12928534/039801f6-3a2a-434d-8dc0-70e2fea69dd8)
Alchemy Stone

**Comment by Razzmatazzz** [comment]
Please post your exported save.

**Comment by chocopool** [comment]
https://remnant2.wiki.fextralife.com/Atom+Splitter

**Comment by razeedazee** [comment]
Diverting Heart

![image](https://github.com/Razzmatazzz/RemnantSaveGuardian/assets/141931230/a39071b9-4755-4633-8adf-cd9a91fd21d6)

![image](https://github.com/Razzmatazzz/RemnantSaveGuardian/assets/141931230/1608e00b-daf4-4ad7-aed7-817090933c78)

Got a pair of saves, before and after activation. The before is 1 world boss kill away from the devs comments that it should be 30 world boss kills.

[diverted-heart.zip](https://github.com/Razzmatazzz/RemnantSaveGuardian/files/12327167/diverted-heart.zip)

**Comment by Dom-1** [comment]
1. "Ghost Shell" mutator is missing.
https://remnant2.wiki.fextralife.com/Ghost+Shell

2. Shotgun should (probably?) be renamed "Ford's Scattergun". Right now it leads to 404 when looking for it on the wiki.
https://remnant2.wiki.fextralife.com/Ford's+Scattergun

**Comment by Razzmatazzz** [comment]
@chocopool do you have the atom splitter? If so, please post your save. 

I'll add these other items when I get back home Sunday.

**Comment by razeedazee** [comment]
I think the saves without the item collected are not as helpful? So i here is one with diverted heart actually collected

[diverting-heart-collected.zip](https://github.com/Razzmatazzz/RemnantSaveGuardian/files/12327817/diverting-heart-collected.zip)

![image](https://github.com/Razzmatazzz/RemnantSaveGuardian/assets/141931230/caf96926-2837-4812-ae6b-d3d4980537cc)

**Comment by Konichuchu** [comment]
Ring : Momentum Driver
Don't have any screen but I modified the code to make it work
File : Game.json
Line 1116 : Instead of "Underworld_TheClaw" put "TheClaw"

**Comment by Chlorox115** [comment]
Ornate Flail https://remnant2.wiki.fextralife.com/Ornate+Flail
Sapphire Dreamstone https://remnant2.wiki.fextralife.com/Sapphire+Dreamstone

Both seem to be part of the Executioner event in Losomn https://remnant2.wiki.fextralife.com/The+Executioner
[saves.zip](https://github.com/Razzmatazzz/RemnantSaveGuardian/files/12328761/saves.zip)
save_0 is after collecting both. Wiki of Sapphire has a description of exactly how I found them

**Comment by crackedmind** [comment]
@Razzmatazzz 
`/Game/World_Fae/Items/Trinkets/Rings/SapphireDreamstone/Ring_SapphireDreamstone`
`/Game/World_Base/Items/Weapons/Melee/Standard/Flail/OrnateFlail/Weapon_OrnateFlail`

**Comment by AndrewSav** [comment]
All mutators that [Dwell](https://remnant2.wiki.fextralife.com/Dwell) sells are not listed.

**Comment by Razzmatazzz** [comment]
I need the exported profile.sav (profile.txt) including a character that has each of these items so I can add them. Not usually possible to tell what they are called in the game files from the world saves.

**Comment by razeedazee** [comment]
I have a profile with all known in game items, except the hardcore/apoc reward stuff

Will that do?

**Comment by crackedmind** [comment]
[profile.txt](https://github.com/Razzmatazzz/RemnantSaveGuardian/files/12329494/profile.txt)
Bought all mutators from Dwell

**Comment by razeedazee** [comment]
@Razzmatazzz actually, this is the save/profile with all ingame items

https://github.com/Razzmatazzz/RemnantSaveGuardian/files/12327817/diverting-heart-collected.zip

![image](https://github.com/Razzmatazzz/RemnantSaveGuardian/assets/141931230/b90e2250-639c-482d-9f01-244386458b1d)

**Comment by Razzmatazzz** [comment]
I need a save with the rotten thaen fruit even so I know where to put the Ghost Shell mutator.

**Comment by razeedazee** [comment]
@Razzmatazzz This one has it in `save_0.sav` as a quest item

[rotten-thaen-fruit.zip](https://github.com/Razzmatazzz/RemnantSaveGuardian/files/12330951/rotten-thaen-fruit.zip)

**Comment by AndrewSav** [comment]
[before Lithic Signet.zip](https://github.com/Razzmatazzz/RemnantSaveGuardian/files/12334435/before.Lithic.Signet.zip)
[Lithic Signet](https://remnant2.wiki.fextralife.com/Lithic+Signet) 
`/Game/World_Jungle/Items/Trinkets/Rings/LithicSignet/Ring_LithicSignet`

This is four statues event linked [here](https://remnant2.wiki.fextralife.com/The+Lament) search for "four statues" on that page.

This is the event where a stone statute pursuits you, when you are not looking at it. It could be that the event here is "/Game/World_Jungle/Quests/Quest_Injectable_Crypt_LivingStone/Quest_Injectable_Crypt_LivingStone" - the area does look like a crypt and Living Stone is apt - the stone statue that lives.

**Comment by Razzmatazzz** [comment]
@razeedazee which boss spawned in the area with the rotten thaen fruit?

**Comment by crackedmind** [comment]
> @razeedazee which boss spawned in the area with the rotten thaen fruit?

https://remnant2.wiki.fextralife.com/Rotten+Thaen+Fruit

No boss.

**Comment by razeedazee** [comment]
@Razzmatazzz

> @razeedazee which boss spawned in the area with the rotten thaen fruit?

This item is in a secret area of the Yaesha = Widows Court area. Using he Red Doe Sigil you open a statue doorway and the item is sitting on top of Altar.

It's not in a box or chest and there is boss but this area usually precede the Corrupter World boss area.

The Specific requirement to access this is Completing the Yaesha World, Giving the [ornate lock box](https://remnant2.wiki.fextralife.com/Ornate+Lockbox) to the queen without opening it and getting the Red Doe Sigil.

**Comment by Razzmatazzz** [comment]
So is this an area you can travel to from The Red Throne, or is it a part of that same map?

**Comment by razeedazee** [comment]
@Razzmatazzz I posted in wrong thread, but i guess it's on topic for that one as well?

https://github.com/Razzmatazzz/RemnantSaveGuardian/issues/44

**Comment by jgh713** [comment]
Re: Lithic Signet, it should be tied to the "WeepingAngels" event, which appears in the world analyzer but doesn't have the item attached to it as a potential reward.

**Comment by Razzmatazzz** [comment]
The Lithic Signet is associated with the Four Statues event, which is `Crypt_LivingStone` in the game's files.

**Comment by AndrewSav** [comment]
Reggie:
- [Nightmare Spiral](https://remnant2.wiki.fextralife.com/Nightmare+Spiral)
- [Bright Steel Ring](https://remnant2.wiki.fextralife.com/Bright+Steel+Ring)

/Game/World_Base/Items/Trinkets/Amulets/NightmareSpiral/Amulet_NightmareSpiral
/Game/World_Base/Items/Trinkets/Rings/BrightSteelRing/Ring_BrightSteelRing

![2023-08-15_16-53-43](https://github.com/Razzmatazzz/RemnantSaveGuardian/assets/658865/5d4e83d5-dbcd-47b2-9053-7d14bc37bac2)
![2023-08-15_16-55-43](https://github.com/Razzmatazzz/RemnantSaveGuardian/assets/658865/2e945ade-4abc-4bd1-87a2-fcf07f1227ab)

**Comment by AndrewSav** [comment]
>>Re: Lithic Signet, it should be tied to the "WeepingAngels" event, which appears in the world analyzer but doesn't have the item attached to it as a potential reward.

> The Lithic Signet is associated with the Four Statues event, which is `Crypt_LivingStone` in the game's files.

It appears that LivingStone and Weeping Angels [is the same thing](https://github.com/Razzmatazzz/RemnantSaveGuardian/blob/914aea81ef38e0ca841a540920831dc1b2b8c935/RemnantSaveGuardian/locales/GameStrings.resx#L642-L643).

**Comment by jgh713** [comment]
Lithic signet is associated with `Crypt_LivingStone`, which doesn't actually appear on save guardian when it's in the world. The `LivingStone` event does, and is recognized by save guardian.

**Comment by AndrewSav** [comment]
That's right, I reported that just above, hopefully someone can fix that.

**Comment by Razzmatazzz** [comment]
This should be fixed in the latest release.

**Comment by AlphaRage** [comment]
> Thanks! Did a `Towers_ElevatorShaft` event appear in that location?

I just had this event but the two items didn't show as missing. They are in the missing items tab but they are not in the missing items column when this event appears.

**Comment by ghostnup** [comment]
@Razzmatazzz @crackedmind 
While playing the game, I can pick up the "Ring Of The Robust" and meet "the Huntress" in Foesaken Quarter, but the World Analyzer does not show them at all.
![屏幕截图 2023-08-14 213500](https://github.com/Razzmatazzz/RemnantSaveGuardian/assets/24566215/19f0f744-a0ee-484a-821e-148987d2e496)

After tracing, I find following codes in RemnantWorldEvent.cs throw them away.

```
            foreach (Match area in areas)
             {
                ...
                var exclusiveTypes = new List<string>() {
                    "Boss",
                    "SideD",
                    "Miniboss",
                    "Point of Interest"
                };
                var exclusiveEvent = areaEvents.Find(e => exclusiveTypes.Contains(e.RawType));
                if (exclusiveEvent != null)
                {
                    if (zoneEvents[currentWorld].FindIndex(e => e._name == exclusiveEvent._name) != -1)
                    {
                        continue;
                    }
                }
                ...
             }
```

I wonder if it's filtering out too much？

This is my exported save of the game's world.
[save_0.zip](https://github.com/Razzmatazzz/RemnantSaveGuardian/files/12363446/save_0.zip)

**Comment by PierreCHT** [comment]
> [Temp.zip](https://github.com/Razzmatazzz/RemnantSaveGuardian/files/12292456/Temp.zip) https://remnant2.wiki.fextralife.com/Propulsion+Loop https://remnant2.wiki.fextralife.com/Low+Yield+Recovery+Ring
> 
> /Game/World_Nerud/Items/Trinkets/Rings/PropulsionLoop/Ring_PropulsionLoop.Ring_PropulsionLoop_C /Game/World_Nerud/Items/Trinkets/Rings/LowYieldRecoveryRing/Ring_LowYieldRecoveryRing.Ring_LowYieldRecoveryRing_C
> 
> N'Erud / Spectrum Nexus First character
> 
> ![20230808172955_1](https://user-images.githubusercontent.com/1228263/259136018-a0b32297-8784-49fc-ad52-5662ac2c7307.jpg)

LowYieldRecoveryRin and PropulsionLoop still missing in ElevatorShaft

**Comment by Razzmatazzz** [comment]
@ghostnup are you sure that's the code that's discarding the rings? That code is intended to ensure that only one boss, side dungeon, or miniboss event are found in a single "area", which I believe should be valid. I also don't see why that filter would be discarding the ring since it isn't any of those types of events.

@PierreCHT thanks, that should be fixed in the next release.

**Comment by Razzmatazzz** [comment]
This build should work out some bugs from the previous:
[RemnantSaveGuardian.zip](https://github.com/Razzmatazzz/RemnantSaveGuardian/files/12371761/RemnantSaveGuardian.zip)

**Comment by Malidictus** [comment]
Ran into an item and an event that Save Guardian did not track. In N'erud, in the [Vault of the Formless](https://remnant2.wiki.fextralife.com/Vault+of+the+Formless), I got the [Robot Hanger](https://remnant2.wiki.fextralife.com/Robot+Hanger) event, from which I picked up the [Excess Couil](https://remnant2.wiki.fextralife.com/Excess+Coil). Neither the event nor the item showed up in the list. Here's a copy of my [save file export](https://www.dropbox.com/scl/fi/67na4kqkinnsdfjdbc2bv/Exports.zip?rlkey=ribycqj3d1y4o24jc5ebqm22s&dl=0).

I should note that the Wiki does not list the Robot Hanger as a potential event in the Vault of the Formless. I can say for a fact that I got this event in this location, as I'm standing there now typing this.

**Comment by razeedazee** [comment]
> Ran into an item and an event that Save Guardian did not track. In N'erud, in the [Vault of the Formless](https://remnant2.wiki.fextralife.com/Vault+of+the+Formless), I got the [Robot Hanger](https://remnant2.wiki.fextralife.com/Robot+Hanger) event, from which I picked up the [Excess Couil](https://remnant2.wiki.fextralife.com/Excess+Coil). Neither the event nor the item showed up in the list. Here's a copy of my [save file export](https://www.dropbox.com/scl/fi/67na4kqkinnsdfjdbc2bv/Exports.zip?rlkey=ribycqj3d1y4o24jc5ebqm22s&dl=0).
> 
> I should note that the Wiki does not list the Robot Hanger as a potential event in the Vault of the Formless. I can say for a fact that I got this event in this location, as I'm standing there now typing this.

The event is there W.D. 109, and that item should show as not owned.

![image](https://github.com/Razzmatazzz/RemnantSaveGuardian/assets/141931230/7d82e166-18e0-4e53-9fb2-a9e8c44b97f7)

**Comment by Razzmatazzz** [comment]
@Malidictus this was from your adventure mode, correct? Here's how that displays with the latest version:
![image](https://github.com/Razzmatazzz/RemnantSaveGuardian/assets/35779878/9e38d4ed-fcd3-48ef-9175-be2df530a4e8)

**Comment by Malidictus** [comment]
> @Malidictus this was from your adventure mode, correct? Here's how your save's adventure mode displays with the latest version: ![image](https://user-images.githubusercontent.com/35779878/261734703-9e38d4ed-fcd3-48ef-9175-be2df530a4e8.png)

Can confirm - the event now shows up in the list. I don't see unowned items, naturally, since I picked those up before reporting the issue. Thank you kindly.

**Comment by AndrewSav** [comment]
[Devoured Loop](https://remnant2.wiki.fextralife.com/Devoured+Loop)

**Comment by IsaacOscar** [comment]
It would be great if Simulacrum would be listed like it was in the old remnant world analyser.

**Comment by ethaldeman** [comment]
The [Shock Device](https://remnant2.wiki.fextralife.com/Shock+Device) appeared in my world, and I believe is a static item in the Morrow Sanatorium; Losom, but was not listed as an item present.

/Game/World_Fae/Items/Trinkets/Amulets/ConductivePadding/Amulet_ShockDevice.Amulet_ShockDevice_C

First Character and Adventure
[save_0.txt](https://github.com/Razzmatazzz/RemnantSaveGuardian/files/12679025/save_0.txt)
[profile.txt](https://github.com/Razzmatazzz/RemnantSaveGuardian/files/12679037/profile.txt)

**Comment by Wuxriff** [comment]
New weapons and mutators was added yesterday with a new update

**Comment by Razzmatazzz** [comment]
If someone wants to submit a PR for the new items, I'll review, merge, and push out a new version.

**Comment by thelownage** [comment]
I'm not sure if the new Mutators corelate one to one with specific aberrations, however I don't believe they do. Which aberrations spawn do appear to be based on the world, and not the specific zone. I don't have everything yet, but if someone with a better idea what they're doing wants it for a PR, I'll just leave these right here...

New material:
[Corrupted Shard](https://remnant2.wiki.fextralife.com/Corrupted+Shard) /Game/World_Base/Items/Materials/LumeniteCrystal/Material_CorruptedShard.Material_CorruptedShard_C

New Weapons available from Dwell back at the Ward:
[Corrupted Aphelion](https://remnant2.wiki.fextralife.com/Corrupted+Aphelion) /Game/World_Base/Items/Weapons/Longguns/Special/CorruptedAphelion/Weapon_CorruptedAphelion.Weapon_CorruptedAphelion_C
[Corrupted Deceit](https://remnant2.wiki.fextralife.com/Corrupted+Deceit) /Game/World_Base/Items/Weapons/Longguns/Special/CorruptedDeceit/Weapon_CorruptedDeceit.Weapon_CorruptedDeceit_C
[Corrupted Merciless](https://remnant2.wiki.fextralife.com/Corrupted+Merciless) /Game/World_Base/Items/Weapons/Longguns/Special/CorruptedMerciless/Weapon_CorruptedMerciless.Weapon_CorruptedMerciless_C
[Corrupted Meridian](https://remnant2.wiki.fextralife.com/Corrupted+Meridian) /Game/World_Base/Items/Weapons/Handguns/Special/CorruptedMeridian/Weapon_CorruptedMeridian.Weapon_CorruptedMeridian_C
[Corrupted Rune Pistol](https://remnant2.wiki.fextralife.com/Corrupted+Rune+Pistol) /Game/World_Base/Items/Weapons/Handguns/Special/CorruptedRunePistol/Weapon_CorruptedRunePistol.Weapon_CorruptedRunePistol_C

New Mutators:
[Bottom Feeder](https://remnant2.wiki.fextralife.com/Bottom Feeder) /Game/World_Base/Items/Gems/Ranged/MetaGems/BottomFeeder/MetaGem_BottomFeeder.MetaGem_BottomFeeder_C
[Bottom Heavy](https://remnant2.wiki.fextralife.com/Bottom Heavy) 
[Edgelord](https://remnant2.wiki.fextralife.com/Edgelord) /Game/World_Base/Items/Gems/Melee/MetaGems/Edgelord/MetaGem_Edgelord.MetaGem_Edgelord_C
[Ingenuity](https://remnant2.wiki.fextralife.com/Ingenuity) /Game/World_Base/Items/Gems/Ranged/MetaGems/Ingenuity/MetaGem_Ingenuity.MetaGem_Ingenuity_C
[Kill Switch](https://remnant2.wiki.fextralife.com/Kill Switch) /Game/World_Base/Items/Gems/Ranged/MetaGems/KillSwitch/MetaGem_KillSwitch.MetaGem_KillSwitch_C
[Latency](https://remnant2.wiki.fextralife.com/Latency) /Game/World_Base/Items/Gems/Melee/MetaGems/Latency/MetaGem_Latency.MetaGem_Latency_C
[Opportunist](https://remnant2.wiki.fextralife.com/Opportunist) /Game/World_Base/Items/Gems/Melee/MetaGems/Opportunist/MetaGem_Opportunist.MetaGem_Opportunist_C
[Sequenced Shot](https://remnant2.wiki.fextralife.com/Sequenced Shot) /Game/World_Base/Items/Gems/Ranged/MetaGems/SequencedShot/MetaGem_SequencedShot.MetaGem_SequencedShot_C
[Shocker](https://remnant2.wiki.fextralife.com/Shocker) /Game/World_Base/Items/Gems/Melee/MetaGems/Shocker/MetaGem_Shocker.MetaGem_Shocker_C
[Spirit Healer](https://remnant2.wiki.fextralife.com/Spirit Healer) 
[Stormbringer](https://remnant2.wiki.fextralife.com/Stormbringer) /Game/World_Base/Items/Gems/Melee/MetaGems/Stormbringer/MetaGem_Stormbringer.MetaGem_Stormbringer_C
[Top Heavy](https://remnant2.wiki.fextralife.com/Top Heavy) /Game/World_Base/Items/Gems/Ranged/MetaGems/TopHeavy/MetaGem_TopHeavy.MetaGem_TopHeavy_C

**Comment by AndrewSav** [comment]
I believe this is the full list of the added mutators, ^^^ there is nothing missing (based on datamining)

**Comment by agudmund-git** [comment]
Does Endaira's end or burden of the follower show up in save guardian? I've been re-rolling yaesha all morning, probably 40 times now, and haven't seen a single Endaira's End show up.

**Comment by Wuxriff** [comment]
> Does Endaira's end or burden of the follower show up in save guardian? I've been re-rolling yaesha all morning, probably 40 times now, and haven't seen a single Endaira's End show up.

It's bugged and will be fixed in future updates.

**Comment by eriklysoe** [comment]
> Does Endaira's end or burden of the follower show up in save guardian? I've been re-rolling yaesha all morning, probably 40 times now, and haven't seen a single Endaira's End show up.

I tried many times, never seen Endaira’s end

**Comment by Malidictus** [comment]
I found a Digested [Hog Lure](https://remnant2.wiki.fextralife.com/Digested+Hog+Lure) in the Forlorn Coast which doesn't show up anywhere in the Save Guardian. Save file as follows:
[Digested Hog Lure.zip](https://github.com/Razzmatazzz/RemnantSaveGuardian/files/13552066/Digested.Hog.Lure.zip)

**Comment by thelownage** [comment]
About to start the One Shot for the new DLC, figured I'd export the save in case anyone wanted to search for any DLC2 items
[save_0.txt](https://github.com/Razzmatazzz/RemnantSaveGuardian/files/15083812/save_0.txt)

**Comment by Silberox** [comment]
Hi, the Pallid Lodestone didnt appear on the world analyzer. I got it after beating the boss "the Stonewarden", its with my first character.
https://remnant2.wiki.fextralife.com/Pallid+Lodestone
[638504701082935232.zip](https://github.com/Razzmatazzz/RemnantSaveGuardian/files/15211268/638504701082935232.zip)

**Comment by karasujigoku** [comment]
Hi, thanks for the awesome tool.

Couple of rings missing::

Burden of the Stargazer - https://remnant2.wiki.fextralife.com/Burden+of+the+Stargazer
A'taerii Booster - https://remnant2.wiki.fextralife.com/A'taerii+Booster

**Comment by Kirbymain001** [comment]
soul guard ring didn't appear with blood moon altar vendor
https://remnant2.wiki.fextralife.com/Soul+Guard

**Comment by Seriousedy** [comment]
Hidden Library Event and item not shown for Earthen Coliseum
https://remnant2.wiki.fextralife.com/The+Hidden+Library
[remnant2-hidden-library.zip](https://github.com/user-attachments/files/17718848/remnant2-hidden-library.zip)
First Character, first time encountering this event and dungeon, just bought the dlc. Haven't played through the stories yet.
